=== Xilinx/XilinxBoardStore/boards/NewWaveDesign/v1163_vc1902/1.0/preset.dtd
<!--
TODO: This needs to be reviewed by Damon and I am very unsure about
both element counts and REQUIRED vs IMPLIED attributes..
TODO: Add DTDDoc (http://dtddoc.sourceforge.net/index.html) comments to this file.

   Change Log:
   9/10/19 - initial creation of this DTD.
-->

<!--
   @title Definition of the preset.xml file used in a Vivado board definition. 
   This file provides a list of predefined IP configuration options for the different IP
   used to implement bus interfaces in a design project.

   Each board file has a specific DOCTYPE declaration with a specific root element. 
   Please ensure that the same syntax is followed while declaring the
   DOCTYPE in your XML files.

   For preset.xml file the correct syntax is:
     <!DOCTYPE ip_presets SYSTEM "path_to_corresponding_dtd_file">

   @root ip_presets
-->

<!-- A ip_presets element should have one or more ip_preset element as it's children. -->
<!ELEMENT ip_presets ( ip_preset+ ) >
<!-- @attr schema version used, should be 1.0 for this version  -->
<!ATTLIST ip_presets schema CDATA #REQUIRED >

<!-- An ip_preset element should have one or more ip elements as it's children. -->
<!ELEMENT ip_preset ( ip+ ) >
<!-- @attr   Identifies the preset process being defined. The preset_proc_name
used here will also be specified in the Board file for interfaces that
implement this preset process.-->
<!ATTLIST ip_preset preset_proc_name CDATA #REQUIRED >

<!ELEMENT ip ( user_parameters | model_parameters ) >
<!-- @attr   Address of the board provider's company website.-->
<!ATTLIST ip vendor CDATA #REQUIRED >
<!-- @attr Library that he core is part of.  -->
<!ATTLIST ip library CDATA #REQUIRED >
<!-- @attr  Name of the IP core. -->
<!ATTLIST ip name CDATA #REQUIRED >
<!-- @attr  Version of the IP.  -->
<!ATTLIST ip version CDATA #IMPLIED >
<!-- @attr  IP interface name. -->
<!ATTLIST ip ip_interface CDATA #IMPLIED >

<!-- Within the <ip> section, the <user_parameters> and <user_parameter> tags define the
various configuration presets to apply to the specified IP core. -->
<!ELEMENT user_parameters ( user_parameter | user_hier_parameter )+ >

<!ELEMENT user_parameter EMPTY >
<!-- @attr  Name of the pre-configured property of the IP core.  -->
<!ATTLIST user_parameter name CDATA #REQUIRED >
<!-- @attr  Preset value of the property.  -->
<!ATTLIST user_parameter value CDATA #REQUIRED >
<!-- @attr  The type of the parameter, string or range.  -->
<!ATTLIST user_parameter value_type CDATA #IMPLIED >

<!-- The user_hier_parameter tag can be used instead of user_parameter when representing
     hierarchical parameters (interoduced for CIPS 3.0)  -->
<!ELEMENT user_hier_parameter ( user_hier_parameter | user_parameter )+ >
<!-- @attr  Name of the user_hier_parameter. This is the only attribute since additional
     information is set via hier elements  -->
<!ATTLIST user_hier_parameter name CDATA #REQUIRED >

<!ELEMENT model_parameters ( model_parameter+ ) >

<!ELEMENT model_parameter EMPTY >
<!ATTLIST model_parameter name CDATA #REQUIRED >
<!ATTLIST model_parameter value CDATA #REQUIRED >
<!ATTLIST model_parameter value_type CDATA #IMPLIED >

=== Xilinx/XilinxBoardStore/boards/NewWaveDesign/v1163_vc1902/1.0/preset.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- Comment out next line after testing complete -->
<!DOCTYPE ip_presets SYSTEM "./preset.dtd">
<!-- Copyright (C) 2024, New Wave Design and Verification
	THIS DOCUMENT AND THE INFORMATION CONTAINED HEREIN IS PROPRIETARY
	AND CONFIDENTIAL TO NEW WAVE DESIGN AND VERIFICATION AND SHALL NOT
	BE USED, DISTRIBUTED OR REPRODUCED FOR ANY PURPOSE, EXCEPT
	WITH THE WRITTEN CONSENT OF NEW WAVE DESIGN AND VERIFICATION. -->

<!-- Preset file:  Provides a list of predefined IP configuration options for the different IP
	used to implement bus interfaces in a design project. The preset file is used by the
	Vivado Design Suite when the IP is customized from the IP catalog and added into the
	design. This file is located in the board repository, in the same folder or directory as the
	Board Interface file.

	17 Jan, 2024 - SBJ - Initial entry.
	-->

<ip_presets schema="1.0">
	<ip_preset preset_proc_name="ps_pmc_fixed_io_preset">
		<ip vendor="xilinx.com" library="ip" name="versal_cips" version="*" ip_interface="FIXED_IO">
			<user_parameters>
				<user_hier_parameter name="CONFIG.PS_PMC_CONFIG">
					<user_hier_parameter name="PMC_MIO11">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="disable"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="AUXIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PMC_MIO12">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="out"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="high"/>
						<user_parameter name="PULL" value="pullup"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="GPIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PMC_MIO24">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="disable"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="AUXIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PMC_MIO25">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="out"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="high"/>
						<user_parameter name="PULL" value="pullup"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="GPIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PMC_OSPI_PERIPHERAL">
						<user_parameter name="ENABLE" value="1"/>
						<user_hier_parameter name="IO">
							<user_parameter name="PMC_MIO" value="0 .. 11"/>
						</user_hier_parameter>
						<user_parameter name="MODE" value="Single"/>
					</user_hier_parameter>
					<user_hier_parameter name="PMC_OT_CHECK">
						<user_parameter name="DELAY" value="0"/>
						<user_parameter name="ENABLE" value="1"/>
					</user_hier_parameter>
					<user_hier_parameter name="PMC_SD0">
						<user_parameter name="CD_ENABLE" value="0"/>
						<user_hier_parameter name="CD_IO">
							<user_parameter name="PMC_MIO" value="24"/>
						</user_hier_parameter>
						<user_parameter name="POW_ENABLE" value="0"/>
						<user_hier_parameter name="POW_IO">
							<user_parameter name="PMC_MIO" value="17"/>
						</user_hier_parameter>
						<user_parameter name="RESET_ENABLE" value="1"/>
						<user_hier_parameter name="RESET_IO">
							<user_parameter name="PMC_MIO" value="17"/>
						</user_hier_parameter>
						<user_parameter name="WP_ENABLE" value="0"/>
						<user_hier_parameter name="WP_IO">
							<user_parameter name="PMC_MIO" value="25"/>
						</user_hier_parameter>
					</user_hier_parameter>
					<user_parameter name="PMC_SD0_DATA_TRANSFER_MODE" value="8Bit"/>
					<user_hier_parameter name="PMC_SD0_PERIPHERAL">
						<user_parameter name="CLK_100_SDR_OTAP_DLY" value="0x00"/>
						<user_parameter name="CLK_200_SDR_OTAP_DLY" value="0x2"/>
						<user_parameter name="CLK_50_DDR_ITAP_DLY" value="0x1E"/>
						<user_parameter name="CLK_50_DDR_OTAP_DLY" value="0x5"/>
						<user_parameter name="CLK_50_SDR_ITAP_DLY" value="0x2C"/>
						<user_parameter name="CLK_50_SDR_OTAP_DLY" value="0x5"/>
						<user_parameter name="ENABLE" value="1"/>
						<user_hier_parameter name="IO">
							<user_parameter name="PMC_MIO" value="13 .. 25"/>
						</user_hier_parameter>
					</user_hier_parameter>
					<user_parameter name="PMC_SD0_SLOT_TYPE" value="eMMC"/>
					<user_parameter name="PS_BANK_2_IO_STANDARD" value="LVCMOS3.3"/>
					<user_parameter name="PS_BANK_3_IO_STANDARD" value="LVCMOS3.3"/>
					<user_hier_parameter name="PS_ENET0_MDIO">
						<user_parameter name="ENABLE" value="1"/>
						<user_hier_parameter name="IO">
							<user_parameter name="PMC_MIO" value="50 .. 51"/>
						</user_hier_parameter>
					</user_hier_parameter>
					<user_hier_parameter name="PS_ENET0_PERIPHERAL">
						<user_parameter name="ENABLE" value="1"/>
						<user_hier_parameter name="IO">
							<user_parameter name="PMC_MIO" value="26 .. 37"/>
						</user_hier_parameter>
					</user_hier_parameter>
					<user_hier_parameter name="PS_ENET1_PERIPHERAL">
						<user_parameter name="ENABLE" value="1"/>
						<user_hier_parameter name="IO">
							<user_parameter name="PMC_MIO" value="38 .. 49"/>
						</user_hier_parameter>
					</user_hier_parameter>
					<user_parameter name="PS_GEN_IPI0_ENABLE" value="1"/>
					<user_parameter name="PS_GEN_IPI1_ENABLE" value="1"/>
					<user_parameter name="PS_GEN_IPI2_ENABLE" value="1"/>
					<user_parameter name="PS_GEN_IPI3_ENABLE" value="1"/>
					<user_parameter name="PS_GEN_IPI4_ENABLE" value="1"/>
					<user_parameter name="PS_GEN_IPI5_ENABLE" value="1"/>
					<user_parameter name="PS_GEN_IPI6_ENABLE" value="1"/>
					<user_hier_parameter name="PS_I2C0_PERIPHERAL">
						<user_parameter name="ENABLE" value="1"/>
						<user_hier_parameter name="IO">
							<user_parameter name="PS_MIO" value="6 .. 7"/>
						</user_hier_parameter>
					</user_hier_parameter>
					<user_hier_parameter name="PS_I2C1_PERIPHERAL">
						<user_parameter name="ENABLE" value="1"/>
						<user_hier_parameter name="IO">
							<user_parameter name="PS_MIO" value="0 .. 1"/>
						</user_hier_parameter>
					</user_hier_parameter>
					<user_hier_parameter name="PS_MIO10">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="disable"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="AUXIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PS_MIO11">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="disable"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="AUXIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PS_MIO13">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="disable"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="AUXIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PS_MIO14">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="disable"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="AUXIO"/>
					</user_hier_parameter>
					<user_hier_parameter name="PS_MIO18">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="pullup"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
						<user_parameter name="USAGE" value="Reserved"/>
					</user_hier_parameter>
					<user_hier_parameter name="PS_MIO19">
						<user_parameter name="AUX_IO" value="0"/>
						<user_parameter name="DIRECTION" value="in"/>
						<user_parameter name="DRIVE_STRENGTH" value="8mA"/>
						<user_parameter name="OUTPUT_DATA" value="default"/>
						<user_parameter name="PULL" value="pullup"/>
						<user_parameter name="SCHMITT" value="0"/>
						<user_parameter name="SLEW" value="slow"/>
