=== Xilinx/XilinxBoardStore/boards/NewWaveDesign/v1163_vc1902/1.1/part0_pins.dtd
<!--
   Version 2.2
   Change Log:
   7/22/2019 - initial creation of this DTD.
   8/13/2020 - add support for design_constrs: dci_cascade and internal_vref.
-->

<!--
   @title Definition of the part0_pins.xml file used in a Vivado board definition. Lists
   the pin names of the Xilinx device, or "fpga" type component, and defines the 
   IOSTANDARDs and package pin locations for these component pins.

   Each board file has a specific DOCTYPE declaration with a specific root element. 
   Please ensure that the same syntax is followed while declaring the
   DOCTYPE in your XML files.

   For part0_pins.xml file the correct syntax is:
     <!DOCTYPE part_info SYSTEM "path_to_corresponding_dtd_file">

   @root part_info
-->

<!-- A part_info element should have one or more pins element as it's children. -->
<!ELEMENT part_info ( pins+, design_constrs? ) >
  <!-- @attr part_name Part identifier.  -->
  <!ATTLIST part_info part_name NMTOKEN #IMPLIED >
  <!-- A pins element should have one or more pin element as it's children. -->
  <!ELEMENT pins ( pin+ ) >
    <!-- A pin element defines a single pin, it has no children. -->
    <!ELEMENT pin EMPTY >
      <!-- @attr pin The component pin name on the Xilinx devices, used in the board 
           interface file. Example: GPIO_DIP_SW2 -->
      <!ATTLIST pin name  NMTOKEN #REQUIRED >
      <!-- @attr pin An index assigned to the pin object in the Pin Map File. Example: 0 -->
      <!ATTLIST pin index  CDATA #REQUIRED >
      <!-- @attr  pin A valid IOSTANDARD for the Xilinx device pin, as defined 
       by the board designer. Valid values include IOSTANDARDs supported by the
       Vivado Design Suite for the specific component pin. Example: LVCMOS25 -->
      <!ATTLIST pin iostandard  CDATA #IMPLIED >
      <!-- @attr pin The pin location on the Xilinx device package. Example: Y29 -->
      <!ATTLIST pin loc  CDATA #REQUIRED >
      <!-- @attr pin  -->
      <!ATTLIST pin drive  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin slew  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin diff_term  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin output_impedance  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin ibuf_low_pwr  CDATA #IMPLIED >
      <!-- @ attr pin  -->
      <!ATTLIST pin odt  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin equalization  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin pre_emphasis  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin dqs_bias  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin delay_value  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin iobdelay  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin lvds_pre_emphasis  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin pull_type  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin voh  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin iobank.internal_vref  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin iobank.dci_cascade  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin pcb_min_delay  CDATA #IMPLIED >
      <!-- @attr pin  -->
      <!ATTLIST pin pcb_max_delay  CDATA #IMPLIED >

  <!-- A design_constrs element encloses one or more design constraint elements
       (eiher dci_cascade or internal_vref). -->
  <!ELEMENT design_constrs ( dci_cascade | internal_vref )+>
    <!-- A dci_cascade represents a DCI_CASCADE constraint on io banks.  
         It requires a master bank id and a list of slave bank IDs. -->
    <!ELEMENT dci_cascade EMPTY>
      <!-- @attr The integer bank id for the master bank of the dci_cascade. -->
      <!ATTLIST dci_cascade master_bank_id CDATA #REQUIRED>
      <!-- @attr A comma-separated sequence of integer bank ids for
           slave banks of the dci_cascade. -->
      <!ATTLIST dci_cascade slave_bank_ids CDATA #REQUIRED>
    <!-- An internal_vref represents an INTERNAL_VREF constraint on io banks.  
         It requires an integer bank id and a voltage. -->
    <!ELEMENT internal_vref EMPTY>
      <!-- @attr The integer bank id for the internal_vref's bank. -->
      <!ATTLIST internal_vref bank_id CDATA #REQUIRED>
      <!-- @attr The floating point VREF voltage for the internal_vref. -->
      <!ATTLIST internal_vref voltage CDATA #REQUIRED>

=== Xilinx/XilinxBoardStore/boards/NewWaveDesign/v6065_vp1702/1.0/part0_pins.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!-- Comment out next line after testing complete -->
<!DOCTYPE part_info SYSTEM "./part0_pins.dtd">
<!-- Copyright (C) 2025, New Wave Design
	THIS DOCUMENT AND THE INFORMATION CONTAINED HEREIN IS PROPRIETARY
	AND CONFIDENTIAL TO NEW WAVE DESIGN AND VERIFICATION AND SHALL NOT
	BE USED, DISTRIBUTED OR REPRODUCED FOR ANY PURPOSE, EXCEPT
	WITH THE WRITTEN CONSENT OF NEW WAVE DESIGN AND VERIFICATION.

	Note that needed pullup/down attributes can not be defined here but are included in xdc file(s).

	28 Apr, 2025 - SBJ - Initial entry.
	-->

<part_info part_name="xcvp1702-vsva3340-2MHP-i-S">
	<pins>
		<pin index="0"		name="pcie_lnk_rxn0"			loc="AK1"									/>
		<pin index="1"		name="pcie_lnk_rxn1"			loc="AL3"									/>
		<pin index="2"		name="pcie_lnk_rxn2"			loc="AM1"									/>
		<pin index="3"		name="pcie_lnk_rxn3"			loc="AN3"									/>
		<pin index="4"		name="pcie_lnk_rxp0"			loc="AK2"									/>
		<pin index="5"		name="pcie_lnk_rxp1"			loc="AL4"									/>
		<pin index="6"		name="pcie_lnk_rxp2"			loc="AM2"									/>
		<pin index="7"		name="pcie_lnk_rxp3"			loc="AN4"									/>
		<pin index="8"		name="pcie_lnk_txn0"			loc="AK6"									/>
		<pin index="9"		name="pcie_lnk_txn1"			loc="AL8"									/>
		<pin index="10"		name="pcie_lnk_txn2"			loc="AM6"									/>
		<pin index="11"		name="pcie_lnk_txn3"			loc="AN8"									/>
		<pin index="12"		name="pcie_lnk_txp0"			loc="AK7"									/>
		<pin index="13"		name="pcie_lnk_txp1"			loc="AL9"									/>
		<pin index="14"		name="pcie_lnk_txp2"			loc="AM7"									/>
		<pin index="15"		name="pcie_lnk_txp3"			loc="AN9"									/>

		<pin index="16"		name="vp_clk100_104_n"			loc="AP10"									/>
		<pin index="17"		name="vp_clk100_104_p"			loc="AP11"									/>
		<pin index="18"		name="pcie_lnk_rxn4"			loc="AP1"									/>
		<pin index="19"		name="pcie_lnk_rxn5"			loc="AR3"									/>
		<pin index="20"		name="pcie_lnk_rxn6"			loc="AT1"									/>
		<pin index="21"		name="pcie_lnk_rxn7"			loc="AU3"									/>
		<pin index="22"		name="pcie_lnk_rxp4"			loc="AP2"									/>
		<pin index="23"		name="pcie_lnk_rxp5"			loc="AR4"									/>
		<pin index="24"		name="pcie_lnk_rxp6"			loc="AT2"									/>
		<pin index="25"		name="pcie_lnk_rxp7"			loc="AU4"									/>
		<pin index="26"		name="pcie_lnk_txn4"			loc="AP6"									/>
		<pin index="27"		name="pcie_lnk_txn5"			loc="AR8"									/>
		<pin index="28"		name="pcie_lnk_txn6"			loc="AT6"									/>
		<pin index="29"		name="pcie_lnk_txn7"			loc="AU8"									/>
		<pin index="30"		name="pcie_lnk_txp4"			loc="AP7"									/>
		<pin index="31"		name="pcie_lnk_txp5"			loc="AR9"									/>
		<pin index="32"		name="pcie_lnk_txp6"			loc="AT7"									/>
		<pin index="33"		name="pcie_lnk_txp7"			loc="AU9"									/>

		<pin index="34"		name="pcie_lnk_rxn8"			loc="AW3"									/>
		<pin index="35"		name="pcie_lnk_rxn9"			loc="AY5"									/>
		<pin index="36"		name="pcie_lnk_rxn10"			loc="AY1"									/>
		<pin index="37"		name="pcie_lnk_rxn11"			loc="BA3"									/>
		<pin index="38"		name="pcie_lnk_rxp8"			loc="AW4"									/>
		<pin index="39"		name="pcie_lnk_rxp9"			loc="AY6"									/>
		<pin index="40"		name="pcie_lnk_rxp10"			loc="AY2"									/>
		<pin index="41"		name="pcie_lnk_rxp11"			loc="BA4"									/>
		<pin index="42"		name="pcie_lnk_txn8"			loc="AW8"									/>
		<pin index="43"		name="pcie_lnk_txn9"			loc="AY10"									/>
		<pin index="44"		name="pcie_lnk_txn10"			loc="BA8"									/>
		<pin index="45"		name="pcie_lnk_txn11"			loc="BB10"									/>
		<pin index="46"		name="pcie_lnk_txp8"			loc="AW9"									/>
		<pin index="47"		name="pcie_lnk_txp9"			loc="AY11"									/>
		<pin index="48"		name="pcie_lnk_txp10"			loc="BA9"									/>
		<pin index="49"		name="pcie_lnk_txp11"			loc="BB11"									/>

		<pin index="50"		name="vp_clk100_102_n"			loc="AW12"									/>
		<pin index="51"		name="vp_clk100_102_p"			loc="AW13"									/>
		<pin index="52"		name="pcie_lnk_rxn12"			loc="BB1"									/>
		<pin index="53"		name="pcie_lnk_rxn13"			loc="BC3"									/>
		<pin index="54"		name="pcie_lnk_rxn14"			loc="BD1"									/>
		<pin index="55"		name="pcie_lnk_rxn15"			loc="BE3"									/>
		<pin index="56"		name="pcie_lnk_rxp12"			loc="BB2"									/>
		<pin index="57"		name="pcie_lnk_rxp13"			loc="BC4"									/>
		<pin index="58"		name="pcie_lnk_rxp14"			loc="BD2"									/>
		<pin index="59"		name="pcie_lnk_rxp15"			loc="BE4"									/>
		<pin index="60"		name="pcie_lnk_txn12"			loc="BB6"									/>
		<pin index="61"		name="pcie_lnk_txn13"			loc="BC8"									/>
		<pin index="62"		name="pcie_lnk_txn14"			loc="BD6"									/>
		<pin index="63"		name="pcie_lnk_txn15"			loc="BE8"									/>
		<pin index="64"		name="pcie_lnk_txp12"			loc="BB7"									/>
		<pin index="65"		name="pcie_lnk_txp13"			loc="BC9"									/>
		<pin index="66"		name="pcie_lnk_txp14"			loc="BD7"									/>
		<pin index="67"		name="pcie_lnk_txp15"			loc="BE9"									/>
		<pin index="68"		name="vp_clk156_106_n"			loc="AF10"									/>
		<pin index="69"		name="vp_clk156_106_p"			loc="AF11"									/>

		<pin index="70"		name="cputp_rx_n"				loc="AJ3"									/>
		<pin index="71"		name="cputp_rx_p"				loc="AJ4"									/>
		<pin index="72"		name="cputp_tx_n"				loc="AJ8"									/>
		<pin index="73"		name="cputp_tx_p"				loc="AJ9"									/>
		<pin index="74"		name="dputp_rx_n"				loc="AH1"									/>
		<pin index="75"		name="dputp_rx_p"				loc="AH2"									/>
		<pin index="76"		name="dputp_tx_n"				loc="AH6"									/>
		<pin index="77"		name="dputp_tx_p"				loc="AH7"									/>
		<pin index="78"		name="vp_clk156_110_n"			loc="AB10"									/>
		<pin index="79"		name="vp_clk156_110_p"			loc="AB11"									/>

		<pin index="80"		name="hss_adj_ref0_n"			loc="Y10"									/>
		<pin index="81"		name="hss_adj_ref0_p"			loc="Y11"									/>
		<pin index="82"		name="hss_lnk0_txclk_n"			loc="T10"									/>
		<pin index="83"		name="hss_lnk0_txclk_p"			loc="T11"									/>
		<pin index="84"		name="hss_lnk1_txclk_n"			loc="N12"									/>
		<pin index="85"		name="hss_lnk1_txclk_p"			loc="N13"									/>
		<pin index="86"		name="vp_clk156_117_n"			loc="L12"									/>
		<pin index="87"		name="vp_clk156_117_p"			loc="L13"									/>
		<pin index="88"		name="vp_clk156_200_n"			loc="BE45"									/>
		<pin index="89"		name="vp_clk156_200_p"			loc="BE44"									/>
		<pin index="90"		name="vp_clk100_201_n"			loc="BB47"									/>
		<pin index="91"		name="vp_clk100_201_p"			loc="BB46"									/>
		<pin index="92"		name="vp_clk156_205_n"			loc="AN45"									/>
		<pin index="93"		name="vp_clk156_205_p"			loc="AN44"									/>
		<pin index="94"		name="hss_adj_ref1_n"			loc="AF47"									/>
		<pin index="95"		name="hss_adj_ref1_p"			loc="AF46"									/>
		<pin index="96"		name="vp_clk156_209_n"			loc="AD47"									/>
		<pin index="97"		name="vp_clk156_209_p"			loc="AD46"									/>
		<pin index="98"		name="vp_clk156_216_n"			loc="R47"									/>
		<pin index="99"		name="vp_clk156_216_p"			loc="R46"									/>

		<pin index="100"	name="lpddr4_0_ca_a0"			loc="BV13"	iostandard="LVSTL_11"			/>
		<pin index="101"	name="lpddr4_0_ca_a1"			loc="BU12"	iostandard="LVSTL_11"			/>
		<pin index="102"	name="lpddr4_0_ca_a2"			loc="BU11"	iostandard="LVSTL_11"			/>
		<pin index="103"	name="lpddr4_0_ca_a3"			loc="BU14"	iostandard="LVSTL_11"			/>
		<pin index="104"	name="lpddr4_0_ca_a4"			loc="BT16"	iostandard="LVSTL_11"			/>
		<pin index="105"	name="lpddr4_0_ca_a5"			loc="BU16"	iostandard="LVSTL_11"			/>
		<pin index="106"	name="lpddr4_0_ca_b0"			loc="BR12"	iostandard="LVSTL_11"			/>
		<pin index="107"	name="lpddr4_0_ca_b1"			loc="BT17"	iostandard="LVSTL_11"			/>
		<pin index="108"	name="lpddr4_0_ca_b2"			loc="BR13"	iostandard="LVSTL_11"			/>
		<pin index="109"	name="lpddr4_0_ca_b3"			loc="BP13"	iostandard="LVSTL_11"			/>
		<pin index="110"	name="lpddr4_0_ca_b4"			loc="BT15"	iostandard="LVSTL_11"			/>
		<pin index="111"	name="lpddr4_0_ca_b5"			loc="BR15"	iostandard="LVSTL_11"			/>
		<pin index="112"	name="lpddr4_0_ck_c_a0"			loc="BV15"	iostandard="DIFF_LVSTL_11"		/>
		<pin index="113"	name="lpddr4_0_ck_c_b0"			loc="BT14"	iostandard="DIFF_LVSTL_11"		/>
		<pin index="114"	name="lpddr4_0_ck_t_a0"			loc="BV14"	iostandard="DIFF_LVSTL_11"		/>
		<pin index="115"	name="lpddr4_0_ck_t_b0"			loc="BR14"	iostandard="DIFF_LVSTL_11"		/>
		<pin index="116"	name="lpddr4_0_cke_a0"			loc="BU17"	iostandard="LVSTL_11"			/>
		<pin index="117"	name="lpddr4_0_cke_a1"			loc="BV16"	iostandard="LVSTL_11"			/>
		<pin index="118"	name="lpddr4_0_cke_b0"			loc="BR17"	iostandard="LVSTL_11"			/>
		<pin index="119"	name="lpddr4_0_cke_b1"			loc="BT12"	iostandard="LVSTL_11"			/>
		<pin index="120"	name="lpddr4_0_cs_a0"			loc="BU13"	iostandard="LVSTL_11"			/>
		<pin index="121"	name="lpddr4_0_cs_a1"			loc="BV11"	iostandard="LVSTL_11"			/>
		<pin index="122"	name="lpddr4_0_cs_b0"			loc="BL16"	iostandard="LVSTL_11"			/>
		<pin index="123"	name="lpddr4_0_cs_b1"			loc="BL12"	iostandard="LVSTL_11"			/>
		<pin index="124"	name="lpddr4_0_dmi_a0"			loc="BN5"	iostandard="LVSTL_11"			/>
		<pin index="125"	name="lpddr4_0_dmi_a1"			loc="BL11"	iostandard="LVSTL_11"			/>
		<pin index="126"	name="lpddr4_0_dmi_b0"			loc="BT10"	iostandard="LVSTL_11"			/>
		<pin index="127"	name="lpddr4_0_dmi_b1"			loc="BK15"	iostandard="LVSTL_11"			/>
		<pin index="128"	name="lpddr4_0_dq_a0"			loc="BP2"	iostandard="LVSTL_11"			/>
		<pin index="129"	name="lpddr4_0_dq_a1"			loc="BR2"	iostandard="LVSTL_11"			/>
		<pin index="130"	name="lpddr4_0_dq_a2"			loc="BN1"	iostandard="LVSTL_11"			/>
		<pin index="131"	name="lpddr4_0_dq_a3"			loc="BP1"	iostandard="LVSTL_11"			/>
		<pin index="132"	name="lpddr4_0_dq_a4"			loc="BT4"	iostandard="LVSTL_11"			/>
		<pin index="133"	name="lpddr4_0_dq_a5"			loc="BU4"	iostandard="LVSTL_11"			/>
